### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by alonsoss** [sirstudly/SpotifyJukebox#1]
I'm getting an TimeoutError while adding a song to the queue
`TimeoutError: Waiting for element to be located By(xpath, //li[contains(@class, 'tracklist-row--highlighted')]//div[contains(@class, 'tracklist-name')])
Wait timed out after 30010ms
    at /Users/Alonso/Downloads/SpotifyJukebox-master/node_modules/selenium-webdriver/lib/webdriver.js:841:17
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  name: 'TimeoutError',
  remoteStacktrace: ''`

**Comment by sirstudly** [comment]
You can't have the mouse cursor in the browser window or it fucks up the track identification.

**Comment by sirstudly** [comment]
ADD_TRACK is now done through the API, not via the web window
